// Generated by LiveScript 1.2.0
var age;
age = function($scope, $http){
  var ref$, w, h, m, ctx1, color;
  ref$ = [$(window).width(), $(window).height(), 20], w = ref$[0], h = ref$[1], m = ref$[2];
  $('#chart1').attr({
    width: w - 40,
    height: h - 120
  });
  ctx1 = $('#chart1')[0].getContext('2d');
  color = d3.scale.category20();
  $scope.chart1 = new Chart(ctx1);
  $scope.raw = {};
  return $http({
    url: 'age-chart.json',
    method: 'GET'
  }).success(function(chd){
    chd.datasets = chd.datasets.filter(function(it){
      return it.label.length > 3 && Math.random() > 0.97;
    });
    chd.datasets.map(function(it){
      var c;
      c = color(it.label);
      return import$(it, {
        fillColor: c,
        strokeColor: c,
        pointColor: c,
        pointStrokeColor: c
      });
    });
    return $scope.chart1.Line(chd, {
      bezierCurveTension: 0.2,
      animation: false,
      datasetFill: false,
      multiTooltipTemplate: "<%= datasetLabel %> - <%= value %>"
    });
  }).error(function(e){
    return console.error(e);
  });
};
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}