// Generated by LiveScript 1.2.0
var main;
main = function($scope, $http){
  var ref$, w, h, m, ctx1;
  ref$ = [$(window).width(), $(window).height(), 20], w = ref$[0], h = ref$[1], m = ref$[2];
  $('#chart1').attr({
    width: w - 40,
    height: h - 120
  });
  ctx1 = $('#chart1')[0].getContext('2d');
  $scope.chart1 = new Chart(ctx1);
  return $http({
    url: 'region.json',
    method: 'GET'
  }).success(function(d){
    var hash, k, v, i$, len$, p, data;
    hash = {};
    for (k in d) {
      v = d[k];
      for (i$ = 0, len$ = v.length; i$ < len$; ++i$) {
        p = v[i$];
        if (hash[p[3]] == null) {
          hash[p[3]] = 0;
        }
        hash[p[3]]++;
      }
    }
    data = {
      labels: (function(){
        var results$ = [];
        for (k in hash) {
          results$.push(k);
        }
        return results$;
      }()),
      datasets: [{
        data: (function(){
          var ref$, results$ = [];
          for (k in ref$ = hash) {
            v = ref$[k];
            results$.push(v);
          }
          return results$;
        }())
      }]
    };
    return $scope.chart1.Bar(data);
  });
};