// Generated by LiveScript 1.2.0
var young;
young = function($scope, $http){
  var m;
  m = 40;
  $scope.rate = {};
  return $http({
    url: 'young-rate.json',
    method: 'GET'
  }).success(function(d){
    var ret, k, v, data, voterate, youngrate, vrscale, yrscale, x$, y$, xtick, z$, ytick, z1$;
    ret = (function(){
      var ref$, results$ = [];
      for (k in ref$ = d) {
        v = ref$[k];
        results$.push([k, v]);
      }
      return results$;
    }()).filter(function(it){
      return it[1].young;
    });
    ret.map(function(it){
      return it[1].youngrate = parseInt(100 * (it[1].young / it[1].total)) / 100;
    });
    ret.map(function(it){
      return it[1].voterate = parseInt(100 * it[1].voterate) / 100;
    });
    ret.sort(function(a, b){
      return a[1].youngrate - b[1].youngrate;
    });
    data = ret.map(function(it){
      return {
        x: it[1].voterate,
        y: it[1].youngrate
      };
    });
    voterate = data.map(function(it){
      return it.x;
    });
    youngrate = data.map(function(it){
      return it.y;
    });
    vrscale = d3.scale.linear().domain([d3.min(voterate), d3.max(voterate)]).range([m, 1000 - m]);
    yrscale = d3.scale.linear().domain([d3.max(youngrate), d3.min(youngrate)]).range([m, 500 - m * 2]);
    x$ = d3.select('#svg').selectAll('circle').data(data);
    x$.exit().remove();
    x$.enter().append('circle');
    y$ = d3.selectAll('circle');
    y$.attr({
      cx: function(it){
        return vrscale(it.x);
      },
      cy: function(it){
        return yrscale(it.y);
      },
      r: 5,
      fill: '#f00'
    });
    xtick = vrscale.ticks(20);
    z$ = d3.select('#svg').selectAll('g.xtick').data(xtick);
    z$.exit().remove();
    z$.enter().append('g').attr('class', 'xtick').each(function(d, i){
      var x$;
      d3.select(this).append('rect').attr({
        x: function(){
          return vrscale(d);
        },
        y: 460,
        width: 1,
        height: 10,
        fill: '#000'
      });
      x$ = d3.select(this).append('text');
      x$.attr({
        x: function(){
          return vrscale(d);
        },
        y: 480,
        "text-anchor": 'middle'
      });
      x$.text(parseInt(100 * d));
      return x$;
    });
    ytick = yrscale.ticks(20);
    z1$ = d3.select('#svg').selectAll('g.ytick').data(ytick);
    z1$.exit().remove();
    z1$.enter().append('g').attr('class', 'ytick').each(function(d, i){
      var x$;
      d3.select(this).append('rect').attr({
        x: 20,
        y: function(){
          return yrscale(d);
        },
        width: 10,
        height: 1,
        fill: '#000'
      });
      x$ = d3.select(this).append('text');
      x$.attr({
        x: 10,
        y: function(){
          return yrscale(d);
        },
        "text-anchor": 'middle',
        "dominant-baseline": "central"
      });
      x$.text(parseInt(100 * d));
      return x$;
    });
    return z1$;
  });
};